import { Task, TeamMember, KPI } from './types';

export const initialTeamMembers: TeamMember[] = [
  {
    id: '1',
    name: 'Ana Benítez',
    role: 'Gerente de Proyectos',
    email: 'ana.benitez@ecomute.com',
    avatar: 'AB',
    color: '#3B82F6',
  },
  {
    id: '2',
    name: 'Carlos Martínez',
    role: 'Técnico de Instalación',
    email: 'carlos.martinez@ecomute.com',
    avatar: 'CM',
    color: '#10B981',
  },
  {
    id: '3',
    name: 'Diana Rojas',
    role: 'Inspectora de Calidad',
    email: 'diana.rojas@ecomute.com',
    avatar: 'DR',
    color: '#F59E0B',
  },
  {
    id: '4',
    name: 'Eduardo González',
    role: 'Ingeniero Acústico',
    email: 'eduardo.gonzalez@ecomute.com',
    avatar: 'EG',
    color: '#8B5CF6',
  },
  {
    id: '5',
    name: 'Fernanda López',
    role: 'Especialista Térmico',
    email: 'fernanda.lopez@ecomute.com',
    avatar: 'FL',
    color: '#EC4899',
  },
];

export const initialTasks: Task[] = [
  {
    id: '1',
    title: 'Instalar paneles acústicos en Sala de Conferencias A',
    description: 'Montar 24 paneles acústicos en paredes y techo',
    status: 'en_progreso',
    priority: 'alta',
    assigneeId: '2',
    projectCategory: 'paneles_acusticos',
    dueDate: '2025-10-10',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-03',
  },
  {
    id: '2',
    title: 'Inspección de calidad del aislamiento térmico Edificio B',
    description: 'Verificar coeficiente térmico y especificaciones de materiales',
    status: 'pendiente',
    priority: 'critica',
    assigneeId: '3',
    projectCategory: 'aislamiento_termico',
    dueDate: '2025-10-05',
    createdAt: '2025-10-02',
    updatedAt: '2025-10-02',
  },
  {
    id: '3',
    title: 'Diseñar solución de insonorización para estudio de grabación',
    description: 'Crear plan integral para insonorización del estudio',
    status: 'en_progreso',
    priority: 'alta',
    assigneeId: '4',
    projectCategory: 'insonorizacion',
    dueDate: '2025-10-08',
    createdAt: '2025-09-28',
    updatedAt: '2025-10-03',
  },
  {
    id: '4',
    title: 'Ordenar materiales para proyecto Complejo de Oficinas',
    description: 'Comprar espuma acústica, barreras térmicas y herrajes de montaje',
    status: 'completado',
    priority: 'media',
    assigneeId: '1',
    projectCategory: 'solucion_integral',
    dueDate: '2025-10-02',
    createdAt: '2025-09-25',
    updatedAt: '2025-10-01',
  },
  {
    id: '5',
    title: 'Realizar pruebas de eficiencia térmica',
    description: 'Probar aislamiento instalado en instalación de almacén',
    status: 'pendiente',
    priority: 'media',
    assigneeId: '5',
    projectCategory: 'aislamiento_termico',
    dueDate: '2025-10-12',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-01',
  },
  {
    id: '6',
    title: 'Presentación al cliente para proyecto Hotel',
    description: 'Presentar propuesta de solución acústica y térmica',
    status: 'pendiente',
    priority: 'alta',
    assigneeId: '1',
    projectCategory: 'solucion_integral',
    dueDate: '2025-10-06',
    createdAt: '2025-10-02',
    updatedAt: '2025-10-02',
  },
  {
    id: '7',
    title: 'Instalar insonorización en apartamento 301',
    description: 'Instalación de insonorización de piso y paredes',
    status: 'completado',
    priority: 'media',
    assigneeId: '2',
    projectCategory: 'insonorizacion',
    dueDate: '2025-09-30',
    createdAt: '2025-09-20',
    updatedAt: '2025-09-30',
  },
  {
    id: '8',
    title: 'Actualizar documentación del proyecto',
    description: 'Documentar mejores prácticas y lecciones aprendidas del Q3',
    status: 'pendiente',
    priority: 'baja',
    assigneeId: '1',
    projectCategory: 'solucion_integral',
    dueDate: '2025-10-15',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-01',
  },
];

export const initialKPIs: KPI[] = [
  {
    id: '1',
    name: 'Tasa de Finalización de Tareas',
    value: 78,
    target: 85,
    unit: '%',
    trend: 'up',
    category: 'productivity',
  },
  {
    id: '2',
    name: 'Controles de Calidad Aprobados',
    value: 92,
    target: 90,
    unit: '%',
    trend: 'up',
    category: 'quality',
  },
  {
    id: '3',
    name: 'Eficiencia de Instalación',
    value: 85,
    target: 80,
    unit: '%',
    trend: 'stable',
    category: 'efficiency',
  },
  {
    id: '4',
    name: 'Utilización de Materiales',
    value: 88,
    target: 90,
    unit: '%',
    trend: 'down',
    category: 'efficiency',
  },
  {
    id: '5',
    name: 'Proyectos a Tiempo',
    value: 82,
    target: 85,
    unit: '%',
    trend: 'up',
    category: 'productivity',
  },
  {
    id: '6',
    name: 'Satisfacción del Cliente',
    value: 94,
    target: 90,
    unit: '%',
    trend: 'up',
    category: 'quality',
  },
];

